### ISSUE TITLE
terminating with uncaught exception of type c10::Error: Method 'subsampling_rate' is not defined (Android app)

### ISSUE THREAD

**Issue by deepak-kumar-iitk** [wenet-e2e/wenet#886] opened 2021-12-24 09:01 UTC
**Describe the bug**

2021-12-24 13:38:53.131 17956-17956/com.mobvoi.wenet E/cpuinfo: chipset detection failed: could not disambiguate different chipsets reported in different system properties
2021-12-24 13:38:54.651 17956-17956/com.mobvoi.wenet E/libc++abi: terminating with uncaught exception of type c10::Error: Method 'subsampling_rate' is not defined.
    Exception raised from get_method at /Users/xyz/gitlab/wenet/runtime/device/android/wenet/app/src/main/cpp/../../../build/pytorch_android-1.10.0.aar/headers/torch/csrc/jit/api/object.h:105 (most recent call first):
    (no backtrace available)
2021-12-24 13:38:54.653 17956-17956/com.mobvoi.wenet A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17956 (om.mobvoi.wenet), pid 17956 (om.mobvoi.wenet)

**To Reproduce**
1. Build model apk in debug model and install on android 
2. Not able to open app and in logcat getting above issue.

**Comment by pengzhendong** [comment] 2021-12-24 09:58
Which pretrained model you used?

**Comment by mdmuneerhasan** [comment] 2021-12-27 09:12
Similar error on my side , 
When I run app my app on redmi note 7 pro it works fine , but when I try to run same app on other devices it throws this exception subsampling rate method not found

**Comment by pengzhendong** [comment] 2021-12-27 09:26
@mdmuneerhasan same pretrained and apk?

**Comment by mdmuneerhasan** [comment] 2021-12-27 09:28
Yes

**Comment by mdmuneerhasan** [comment] 2022-03-01 10:19
Hi this issue was encountering when I was building apk using my PC , but when I try to build this app on my friends machine , it works fine . I think the problem is due to Cmake or any other library which is system based issue .

**Comment by xingchensong** [comment] 2023-02-21 05:07
solved, close this issue

**Closed by xingchensong** 2023-02-21 05:07 UTC
